"""GPU-accelerated ACES color space rendering using PyOpenGL and OpenColorIO.

This module provides headless GPU rendering for ACES-to-display transforms
using OpenGL shaders generated by OCIO. Supports both interactive and batch
processing of images.
"""

from __future__ import annotations

import ctypes
import logging
import time
from pathlib import Path
from typing import Optional

import numpy as np
import OpenImageIO as oiio
import PyOpenColorIO as ocio
from OpenGL import GL

try:
    from OpenGL.EGL import (
        eglGetDisplay,
        eglInitialize,
        eglChooseConfig,
        eglCreateContext,
        eglMakeCurrent,
        eglSwapBuffers,
        eglCreatePbufferSurface,
        eglBindAPI,
    )
    from OpenGL.EGL import (
        EGL_OPENGL_API,
        EGL_OPENGL_BIT,
        EGL_SURFACE_TYPE,
        EGL_PBUFFER_BIT,
        EGL_RENDERABLE_TYPE,
        EGL_RED_SIZE,
        EGL_GREEN_SIZE,
        EGL_BLUE_SIZE,
        EGL_ALPHA_SIZE,
        EGL_DEPTH_SIZE,
        EGL_NONE,
        EGL_DEFAULT_DISPLAY,
        EGL_CONTEXT_CLIENT_VERSION,
    )
    EGL_AVAILABLE = True
except ImportError:
    EGL_AVAILABLE = False

logger = logging.getLogger(__name__)


# GLSL Shader Sources (from OCIO pyociodisplay)
GLSL_VERT_SRC = """#version 400 core
uniform mat4 mvpMat;
in vec3 in_position;
in vec2 in_texCoord;

out vec2 vert_texCoord;

void main() {
    vert_texCoord = in_texCoord;
    gl_Position = mvpMat * vec4(in_position, 1.0);
}
"""

GLSL_FRAG_SRC = """#version 400 core
uniform sampler2D imageTex;
in vec2 vert_texCoord;

out vec4 frag_color;

void main() {
    frag_color = texture(imageTex, vert_texCoord);
}
"""

GLSL_FRAG_OCIO_SRC_FMT = """#version 400 core
uniform sampler2D imageTex;
in vec2 vert_texCoord;

out vec4 frag_color;

{ocio_src}

void main() {{
    vec4 inColor = texture(imageTex, vert_texCoord);
    vec4 outColor = OCIOMain(inColor);
    frag_color = outColor;
}}
"""


class ACESGPURenderer:
    """Headless GPU renderer for ACES-to-display transformations.

    Uses OpenGL shaders generated by OpenColorIO for real-time color transforms.
    Supports batch processing of images with performance monitoring.

    Example:
        >>> renderer = ACESGPURenderer()
        >>> result = renderer.process_image(
        ...     "input.exr",
        ...     display="sRGB - Display",
        ...     view="ACES 2.0 - SDR 100 nits (Rec.709)"
        ... )
        >>> result.shape  # (height, width, 4)
    """

    def __init__(self, headless: bool = True) -> None:
        """Initialize GPU renderer.

        Args:
            headless: If True, use EGL for headless rendering. If False,
                     attempt to use existing display context.

        Raises:
            RuntimeError: If OpenGL initialization fails.
        """
        self._gl_ready = False
        self._headless = headless
        self._display = None
        self._surface = None
        self._context = None

        # OpenGL resources
        self._shader_program: Optional[int] = None
        self._vao: Optional[int] = None
        self._image_tex: Optional[int] = None  # Input texture (read-only sampler)
        self._output_tex: Optional[int] = None  # Output texture (framebuffer attachment)
        self._framebuffer: Optional[int] = None
        self._renderbuffer: Optional[int] = None

        # OCIO resources
        self._ocio_shader_desc: Optional[ocio.GpuShaderDesc] = None
        self._ocio_tex_ids: list = []
        self._ocio_uniform_ids: dict = {}
        self._ocio_tex_start_index = 1  # Start after image texture (unit 0)

        # Shader cache: (input_cs, display, view) -> compiled_program_id
        self._shader_cache: dict = {}
        self._current_cache_key: Optional[tuple] = None

        # Image metadata
        self._image_width = 0
        self._image_height = 0

        self._initialize_gl()

    def _initialize_gl(self) -> None:
        """Initialize OpenGL context and resources."""
        if self._headless and EGL_AVAILABLE:
            self._initialize_egl()
        else:
            logger.warning(
                "EGL not available, attempting fallback (may fail on headless systems)"
            )
            # Assume context already exists (e.g., in notebook with display)
            self._gl_ready = True

    def _initialize_egl(self) -> None:
        """Initialize EGL context for headless rendering."""
        try:
            eglBindAPI(EGL_OPENGL_API)
            self._display = eglGetDisplay(EGL_DEFAULT_DISPLAY)

            if not self._display:
                raise RuntimeError("Could not get EGL display")

            major, minor = ctypes.c_int(), ctypes.c_int()
            if not eglInitialize(self._display, major, minor):
                raise RuntimeError("Could not initialize EGL")

            logger.info(f"EGL initialized: version {major.value}.{minor.value}")

            # Choose config for RGBA, 32-bit float
            config_attribs = [
                EGL_SURFACE_TYPE,
                EGL_PBUFFER_BIT,
                EGL_RENDERABLE_TYPE,
                EGL_OPENGL_BIT,
                EGL_RED_SIZE,
                8,
                EGL_GREEN_SIZE,
                8,
                EGL_BLUE_SIZE,
                8,
                EGL_ALPHA_SIZE,
                8,
                EGL_DEPTH_SIZE,
                24,
                EGL_NONE,
            ]
            config_attribs_array = (ctypes.c_int * len(config_attribs))(*config_attribs)

            config = ctypes.c_void_p()
            config_count = ctypes.c_int()

            if not eglChooseConfig(
                self._display,
                config_attribs_array,
                ctypes.byref(config),
                1,
                ctypes.byref(config_count),
            ):
                raise RuntimeError("Could not choose EGL config")

            # Create context
            context_attribs = [EGL_CONTEXT_CLIENT_VERSION, 4, EGL_NONE]
            context_attribs_array = (ctypes.c_int * len(context_attribs))(
                *context_attribs
            )

            self._context = eglCreateContext(
                self._display, config, None, context_attribs_array
            )

            if not self._context:
                raise RuntimeError("Could not create EGL context")

            # Create surface (pbuffer for offscreen rendering)
            surface_attribs = [
                12344,  # EGL_WIDTH
                1024,
                12345,  # EGL_HEIGHT
                1024,
                EGL_NONE,
            ]
            surface_attribs_array = (ctypes.c_int * len(surface_attribs))(
                *surface_attribs
            )

            self._surface = eglCreatePbufferSurface(
                self._display, config, surface_attribs_array
            )

            if not self._surface:
                raise RuntimeError("Could not create EGL pbuffer surface")

            if not eglMakeCurrent(
                self._display, self._surface, self._surface, self._context
            ):
                raise RuntimeError("Could not make EGL context current")

            logger.info("EGL headless context initialized successfully")
            self._gl_ready = True

        except Exception as e:
            logger.error(f"EGL initialization failed: {e}")
            raise RuntimeError(f"Failed to initialize EGL: {e}")

    def _compile_shader(self, glsl_src: str, shader_type: int) -> Optional[int]:
        """Compile GLSL shader.

        Args:
            glsl_src: GLSL source code.
            shader_type: GL_VERTEX_SHADER or GL_FRAGMENT_SHADER.

        Returns:
            Shader program ID or None if compilation fails.
        """
        shader = GL.glCreateShader(shader_type)
        GL.glShaderSource(shader, glsl_src)
        GL.glCompileShader(shader)

        if not GL.glGetShaderiv(shader, GL.GL_COMPILE_STATUS):
            log = GL.glGetShaderInfoLog(shader)
            logger.error(f"Shader compilation failed: {log}")
            return None

        return shader

    def _build_shader_program_cached(
        self, frag_src: str, input_cs: str, display: str, view: str
    ) -> bool:
        """Build shader program with caching.

        Caches compiled shaders by (input_colorspace, display, view) to avoid
        recompiling for repeated transforms.

        Args:
            frag_src: Fragment shader source code.
            input_cs: Input color space name (for cache key).
            display: Display device name (for cache key).
            view: View transform name (for cache key).

        Returns:
            True if successful (either cached or newly compiled).
        """
        cache_key = (input_cs, display, view)
        
        # Check if already cached
        if cache_key in self._shader_cache:
            self._shader_program = self._shader_cache[cache_key]
            self._current_cache_key = cache_key
            logger.info(f"Shader program cache hit: {cache_key}")
            return True
        
        # Not cached - compile and store
        if not self._build_shader_program(frag_src):
            return False
        
        # Store in cache
        self._shader_cache[cache_key] = self._shader_program
        self._current_cache_key = cache_key
        logger.info(f"Shader program cached: {cache_key}")
        return True

    def clear_shader_cache(self) -> None:
        """Clear all cached shader programs."""
        for prog_id in self._shader_cache.values():
            GL.glDeleteProgram(prog_id)
        self._shader_cache.clear()
        self._current_cache_key = None
        logger.info("Shader cache cleared")

    def _build_shader_program(self, frag_src: str) -> bool:
        """Build complete shader program.

        Args:
            frag_src: Fragment shader source code.

        Returns:
            True if successful, False otherwise.
        """
        if not self._gl_ready:
            return False

        # Compile shaders
        vert = self._compile_shader(GLSL_VERT_SRC, GL.GL_VERTEX_SHADER)
        if not vert:
            return False

        frag = self._compile_shader(frag_src, GL.GL_FRAGMENT_SHADER)
        if not frag:
            GL.glDeleteShader(vert)
            return False

        # Create program
        program = GL.glCreateProgram()
        GL.glAttachShader(program, vert)
        GL.glAttachShader(program, frag)

        GL.glBindAttribLocation(program, 0, "in_position")
        GL.glBindAttribLocation(program, 1, "in_texCoord")

        GL.glLinkProgram(program)

        if not GL.glGetProgramiv(program, GL.GL_LINK_STATUS):
            log = GL.glGetProgramInfoLog(program)
            logger.error(f"Shader program linking failed: {log}")
            GL.glDeleteprogram(program)
            return False

        # Clean up old program
        if self._shader_program:
            GL.glDeleteProgram(self._shader_program)

        self._shader_program = program
        GL.glDeleteShader(vert)
        GL.glDeleteShader(frag)

        logger.info("Shader program built successfully")
        return True

    def _setup_quad_geometry(self) -> bool:
        """Set up screen-aligned quad for rendering.

        Returns:
            True if successful.
        """
        if self._vao:
            GL.glDeleteVertexArrays(1, [self._vao])

        self._vao = GL.glGenVertexArrays(1)
        GL.glBindVertexArray(self._vao)

        # Positions
        positions = np.array(
            [
                -1.0,
                1.0,
                0.0,  # top-left
                1.0,
                1.0,
                0.0,  # top-right
                1.0,
                -1.0,
                0.0,  # bottom-right
                -1.0,
                -1.0,
                0.0,  # bottom-left
            ],
            dtype=np.float32,
        )

        # Texture coordinates mapping vertices to image coordinates.
        # Following AcademySoftwareFoundation/pyociodisplay standard:
        # vertex: (-1,  1) [TL] -> uv: (0, 1) [TL]
        # vertex: ( 1,  1) [TR] -> uv: (1, 1) [TR]
        # vertex: ( 1, -1) [BR] -> uv: (1, 0) [BR]
        # vertex: (-1, -1) [BL] -> uv: (0, 0) [BL]
        texcoords = np.array(
            [
                0.0, 1.0,  # top-left
                1.0, 1.0,  # top-right
                1.0, 0.0,  # bottom-right
                0.0, 0.0,  # bottom-left
            ],
            dtype=np.float32,
        )

        # Indices
        indices = np.array([0, 1, 2, 0, 2, 3], dtype=np.uint32)

        # Create VBOs
        pos_vbo, tc_vbo, idx_vbo = GL.glGenBuffers(3)

        # Position
        GL.glBindBuffer(GL.GL_ARRAY_BUFFER, pos_vbo)
        GL.glBufferData(GL.GL_ARRAY_BUFFER, positions.nbytes, positions, GL.GL_STATIC_DRAW)
        GL.glVertexAttribPointer(0, 3, GL.GL_FLOAT, GL.GL_FALSE, 0, ctypes.c_void_p(0))
        GL.glEnableVertexAttribArray(0)

        # Texcoords
        GL.glBindBuffer(GL.GL_ARRAY_BUFFER, tc_vbo)
        GL.glBufferData(GL.GL_ARRAY_BUFFER, texcoords.nbytes, texcoords, GL.GL_STATIC_DRAW)
        GL.glVertexAttribPointer(1, 2, GL.GL_FLOAT, GL.GL_FALSE, 0, ctypes.c_void_p(0))
        GL.glEnableVertexAttribArray(1)

        # Index buffer
        GL.glBindBuffer(GL.GL_ELEMENT_ARRAY_BUFFER, idx_vbo)
        GL.glBufferData(GL.GL_ELEMENT_ARRAY_BUFFER, indices.nbytes, indices, GL.GL_STATIC_DRAW)

        GL.glBindVertexArray(0)
        return True

    def _setup_framebuffer(self, width: int, height: int) -> bool:
        """Set up framebuffer for offscreen rendering.

        Args:
            width: Render target width.
            height: Render target height.

        Returns:
            True if successful.
        """
        # Create output texture (framebuffer attachment)
        if self._output_tex:
            GL.glDeleteTextures([self._output_tex])

        self._output_tex = GL.glGenTextures(1)
        GL.glBindTexture(GL.GL_TEXTURE_2D, self._output_tex)
        GL.glTexImage2D(
            GL.GL_TEXTURE_2D,
            0,
            GL.GL_RGB32F,
            width,
            height,
            0,
            GL.GL_RGB,
            GL.GL_FLOAT,
            None,
        )
        GL.glTexParameteri(GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MIN_FILTER, GL.GL_LINEAR)
        GL.glTexParameteri(GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MAG_FILTER, GL.GL_LINEAR)
        GL.glBindTexture(GL.GL_TEXTURE_2D, 0)

        # Create framebuffer
        if self._framebuffer:
            GL.glDeleteFramebuffers(1, [self._framebuffer])

        self._framebuffer = GL.glGenFramebuffers(1)
        GL.glBindFramebuffer(GL.GL_FRAMEBUFFER, self._framebuffer)
        GL.glFramebufferTexture2D(
            GL.GL_FRAMEBUFFER,
            GL.GL_COLOR_ATTACHMENT0,
            GL.GL_TEXTURE_2D,
            self._output_tex,
            0,
        )

        # Create renderbuffer for depth
        if self._renderbuffer:
            GL.glDeleteRenderbuffers(1, [self._renderbuffer])

        self._renderbuffer = GL.glGenRenderbuffers(1)
        GL.glBindRenderbuffer(GL.GL_RENDERBUFFER, self._renderbuffer)
        GL.glRenderbufferStorage(GL.GL_RENDERBUFFER, GL.GL_DEPTH_COMPONENT32F, width, height)
        GL.glFramebufferRenderbuffer(
            GL.GL_FRAMEBUFFER, GL.GL_DEPTH_ATTACHMENT, GL.GL_RENDERBUFFER, self._renderbuffer
        )

        if GL.glCheckFramebufferStatus(GL.GL_FRAMEBUFFER) != GL.GL_FRAMEBUFFER_COMPLETE:
            logger.error("Framebuffer incomplete")
            return False

        GL.glBindFramebuffer(GL.GL_FRAMEBUFFER, 0)
        return True

    def process_image(
        self,
        image_path: str | Path,
        display: str | None = None,
        view: str | None = None,
        exposure: float = 0.0,
        input_colorspace: str | None = None,
    ) -> np.ndarray:
        """Process image with ACES-to-display GPU transform.

        Args:
            image_path: Path to input image (ACES EXR).
            display: OCIO display device name. If None, uses first available.
            view: OCIO view transform name. If None, uses first available for display.
            exposure: Exposure adjustment in stops.
            input_colorspace: Input color space. If None, attempts to detect or use first available.

        Returns:
            RGB image as numpy array with dtype float32, values in [0, 1].

        Raises:
            RuntimeError: If processing fails.
        """
        if not self._gl_ready:
            raise RuntimeError("OpenGL not initialized")

        image_path = Path(image_path)

        # Load image with OIIO
        buf = oiio.ImageBuf(str(image_path))
        if not buf.initialized:
            raise RuntimeError(f"Failed to load image: {image_path}")

        spec = buf.spec()
        width, height, nchannels = spec.width, spec.height, spec.nchannels

        logger.info(f"Loaded image: {width}x{height}, {nchannels} channels")

        # Optimize channel handling: keep RGB as RGB to avoid expensive conversion
        if nchannels >= 3:
            # Already has RGB - keep as is (skip expensive OIIO conversion)
            image_data = buf.get_pixels(oiio.FLOAT)
            image_data = np.asarray(image_data, dtype=np.float32)
            # Use only first 3 channels if more than RGB
            if nchannels > 3:
                image_data = np.ascontiguousarray(image_data[:, :, :3])
            else:
                image_data = np.ascontiguousarray(image_data)
            final_nchannels = 3
        else:
            # Image has fewer than 3 channels (mono/stereo) - pad to RGB
            buf = oiio.ImageBufAlgo.channels(
                buf,
                tuple(list(range(nchannels)) + [0.0] * (3 - nchannels)),
                newchannelnames=("R", "G", "B"),
            )
            image_data = buf.get_pixels(oiio.FLOAT)
            image_data = np.asarray(image_data, dtype=np.float32)
            final_nchannels = 3

        # Setup GPU resources
        self._image_width = width
        self._image_height = height

        if not self._setup_framebuffer(width, height):
            raise RuntimeError("Failed to setup framebuffer")

        if not self._setup_quad_geometry():
            raise RuntimeError("Failed to setup geometry")

        # Allocate input texture (separate from framebuffer output)
        if self._image_tex:
            GL.glDeleteTextures([self._image_tex])
        
        self._image_tex = GL.glGenTextures(1)
        GL.glBindTexture(GL.GL_TEXTURE_2D, self._image_tex)
        GL.glTexParameteri(GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MIN_FILTER, GL.GL_LINEAR)
        GL.glTexParameteri(GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MAG_FILTER, GL.GL_LINEAR)
        GL.glBindTexture(GL.GL_TEXTURE_2D, 0)

        # Upload image data to GPU texture (RGB only - no alpha needed)
        GL.glBindTexture(GL.GL_TEXTURE_2D, self._image_tex)
        if final_nchannels == 3:
            # RGB format - saves 25% bandwidth vs RGBA
            GL.glTexImage2D(
                GL.GL_TEXTURE_2D,
                0,
                GL.GL_RGB32F,
                width,
                height,
                0,
                GL.GL_RGB,
                GL.GL_FLOAT,
                image_data.ravel(),
            )
        else:
            # Fallback for other formats (shouldn't reach here)
            GL.glTexImage2D(
                GL.GL_TEXTURE_2D,
                0,
                GL.GL_RGBA32F,
                width,
                height,
                0,
                GL.GL_RGBA,
                GL.GL_FLOAT,
                image_data.ravel(),
            )

        # Get OCIO config and auto-detect if not specified
        config = ocio.GetCurrentConfig()
        
        # Auto-detect input color space
        if input_colorspace is None:
            color_spaces = [cs.getName() for cs in config.getColorSpaces()]
            if "ACES2065-1" in color_spaces:
                input_colorspace = "ACES2065-1"
            elif "ACEScg" in color_spaces:
                input_colorspace = "ACEScg"
            elif "raw" in color_spaces:
                input_colorspace = "raw"
            elif color_spaces:
                input_colorspace = color_spaces[0]
            else:
                raise RuntimeError("No color spaces available in OCIO config")
        
        # Auto-detect display and view
        if display is None:
            displays = list(config.getDisplays())
            if not displays:
                raise RuntimeError("No displays available in OCIO config")
            display = displays[0]
        
        if view is None:
            views = list(config.getViews(display))
            if not views:
                raise RuntimeError(f"No views available for display '{display}'")
            view = views[0]
        
        logger.info(f"Using: input_colorspace={input_colorspace}, display={display}, view={view}")

        # Build OCIO processor
        display_view_tr = ocio.DisplayViewTransform(src=input_colorspace, display=display, view=view)

        viewing_pipeline = ocio.LegacyViewingPipeline()
        # Skip LinearCC to avoid requiring scene_linear role
        viewing_pipeline.setDisplayViewTransform(display_view_tr)

        processor = viewing_pipeline.getProcessor(config)
        gpu_processor = processor.getDefaultGPUProcessor()

        # Create shader desc
        self._ocio_shader_desc = ocio.GpuShaderDesc.CreateShaderDesc(
            language=ocio.GPU_LANGUAGE_GLSL_4_0
        )
        gpu_processor.extractGpuShaderInfo(self._ocio_shader_desc)

        # Build shader with OCIO code
        ocio_shader_text = self._ocio_shader_desc.getShaderText()
        frag_src = GLSL_FRAG_OCIO_SRC_FMT.format(ocio_src=ocio_shader_text)

        if not self._build_shader_program_cached(frag_src, input_colorspace, display, view):
            raise RuntimeError("Failed to build shader program")

        # Allocate OCIO LUT textures
        if not self._allocate_ocio_tex():
            raise RuntimeError("Failed to allocate OCIO textures")

        # Render
        GL.glBindFramebuffer(GL.GL_FRAMEBUFFER, self._framebuffer)
        GL.glViewport(0, 0, width, height)
        GL.glClearColor(0.0, 0.0, 0.0, 1.0)
        GL.glClear(GL.GL_COLOR_BUFFER_BIT)

        GL.glUseProgram(self._shader_program)

        # Set uniforms
        mvp = np.identity(4, dtype=np.float32)
        mvp_loc = GL.glGetUniformLocation(self._shader_program, "mvpMat")
        GL.glUniformMatrix4fv(mvp_loc, 1, GL.GL_FALSE, mvp)

        # Bind image texture
        GL.glActiveTexture(GL.GL_TEXTURE0)
        GL.glBindTexture(GL.GL_TEXTURE_2D, self._image_tex)
        img_tex_loc = GL.glGetUniformLocation(self._shader_program, "imageTex")
        GL.glUniform1i(img_tex_loc, 0)

        # Bind OCIO LUT textures and uniforms
        self._use_ocio_tex()

        # Draw quad
        GL.glBindVertexArray(self._vao)
        GL.glDrawElements(GL.GL_TRIANGLES, 6, GL.GL_UNSIGNED_INT, ctypes.c_void_p(0))

        # Read back pixels (RGB only, drop alpha)
        GL.glReadBuffer(GL.GL_COLOR_ATTACHMENT0)
        result = GL.glReadPixels(0, 0, width, height, GL.GL_RGB, GL.GL_FLOAT)
        result = np.frombuffer(result, dtype=np.float32).reshape((height, width, 3))

        logger.info(f"GPU rendering complete: {width}x{height}x3")

        return result

    def process_image_profiled(
        self,
        image_path: str | Path,
        display: str | None = None,
        view: str | None = None,
        exposure: float = 0.0,
        input_colorspace: str | None = None,
    ) -> tuple[np.ndarray, dict]:
        """Process image with detailed timing profiling.

        Returns:
            Tuple of (result_image, timing_dict) where timing_dict contains
            breakdowns of: image_load, channel_convert, framebuffer_setup,
            quad_setup, image_upload, ocio_config, shader_compile, lut_allocation,
            render_setup, draw_call, pixel_readback, total.
        """
        if not self._gl_ready:
            raise RuntimeError("OpenGL not initialized")

        timings = {}
        t_start = time.time()
        
        image_path = Path(image_path)

        # === IMAGE LOAD ===
        t = time.time()
        buf = oiio.ImageBuf(str(image_path))
        if not buf.initialized:
            raise RuntimeError(f"Failed to load image: {image_path}")
        spec = buf.spec()
        width, height, nchannels = spec.width, spec.height, spec.nchannels
        timings["image_load"] = (time.time() - t) * 1000

        logger.info(f"Loaded image: {width}x{height}, {nchannels} channels")

        # === CHANNEL CONVERSION (OPTIMIZED: keep RGB as RGB) ===
        t = time.time()
        if nchannels >= 3:
            # Already has RGB - keep as is (skip expensive OIIO conversion)
            image_data = buf.get_pixels(oiio.FLOAT)
            image_data = np.asarray(image_data, dtype=np.float32)
            # Use only first 3 channels if more than RGB
            if nchannels > 3:
                image_data = np.ascontiguousarray(image_data[:, :, :3])
            else:
                image_data = np.ascontiguousarray(image_data)
            final_nchannels = 3
        else:
            # Image has fewer than 3 channels (mono/stereo) - pad to RGB
            buf = oiio.ImageBufAlgo.channels(
                buf,
                tuple(list(range(nchannels)) + [0.0] * (3 - nchannels)),
                newchannelnames=("R", "G", "B"),
            )
            image_data = buf.get_pixels(oiio.FLOAT)
            image_data = np.asarray(image_data, dtype=np.float32)
            final_nchannels = 3
        timings["channel_convert"] = (time.time() - t) * 1000

        # === FRAMEBUFFER SETUP ===
        t = time.time()
        self._image_width = width
        self._image_height = height
        if not self._setup_framebuffer(width, height):
            raise RuntimeError("Failed to setup framebuffer")
        timings["framebuffer_setup"] = (time.time() - t) * 1000

        # === QUAD GEOMETRY SETUP ===
        t = time.time()
        if not self._setup_quad_geometry():
            raise RuntimeError("Failed to setup geometry")
        timings["quad_setup"] = (time.time() - t) * 1000

        # === INPUT TEXTURE ALLOCATION ===
        # Allocate input texture (separate from framebuffer output)
        if self._image_tex:
            GL.glDeleteTextures([self._image_tex])
        
        self._image_tex = GL.glGenTextures(1)
        GL.glBindTexture(GL.GL_TEXTURE_2D, self._image_tex)
        GL.glTexParameteri(GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MIN_FILTER, GL.GL_LINEAR)
        GL.glTexParameteri(GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MAG_FILTER, GL.GL_LINEAR)
        GL.glBindTexture(GL.GL_TEXTURE_2D, 0)

        # === IMAGE TEXTURE UPLOAD (RGB only - no alpha needed) ===
        t = time.time()
        GL.glBindTexture(GL.GL_TEXTURE_2D, self._image_tex)
        if final_nchannels == 3:
            # RGB format - saves 25% bandwidth vs RGBA
            GL.glTexImage2D(
                GL.GL_TEXTURE_2D,
                0,
                GL.GL_RGB32F,
                width,
                height,
                0,
                GL.GL_RGB,
                GL.GL_FLOAT,
                image_data.ravel(),
            )
        else:
            # Fallback for other formats (shouldn't reach here)
            GL.glTexImage2D(
                GL.GL_TEXTURE_2D,
                0,
                GL.GL_RGBA32F,
                width,
                height,
                0,
                GL.GL_RGBA,
                GL.GL_FLOAT,
                image_data.ravel(),
            )
        timings["image_upload"] = (time.time() - t) * 1000

        # === OCIO CONFIG SETUP ===
        t = time.time()
        config = ocio.GetCurrentConfig()
        
        if input_colorspace is None:
            color_spaces = [cs.getName() for cs in config.getColorSpaces()]
            if "ACES2065-1" in color_spaces:
                input_colorspace = "ACES2065-1"
            elif "ACEScg" in color_spaces:
                input_colorspace = "ACEScg"
            elif "raw" in color_spaces:
                input_colorspace = "raw"
            elif color_spaces:
                input_colorspace = color_spaces[0]
            else:
                raise RuntimeError("No color spaces available in OCIO config")
        
        if display is None:
            displays = list(config.getDisplays())
            if not displays:
                raise RuntimeError("No displays available in OCIO config")
            display = displays[0]
        
        if view is None:
            views = list(config.getViews(display))
            if not views:
                raise RuntimeError(f"No views available for display '{display}'")
            view = views[0]
        
        logger.info(f"Using: input_colorspace={input_colorspace}, display={display}, view={view}")
        
        display_view_tr = ocio.DisplayViewTransform(src=input_colorspace, display=display, view=view)
        viewing_pipeline = ocio.LegacyViewingPipeline()
        viewing_pipeline.setDisplayViewTransform(display_view_tr)
        processor = viewing_pipeline.getProcessor(config)
        gpu_processor = processor.getDefaultGPUProcessor()
        timings["ocio_config"] = (time.time() - t) * 1000

        # === SHADER COMPILATION ===
        t = time.time()
        self._ocio_shader_desc = ocio.GpuShaderDesc.CreateShaderDesc(
            language=ocio.GPU_LANGUAGE_GLSL_4_0
        )
        gpu_processor.extractGpuShaderInfo(self._ocio_shader_desc)
        ocio_shader_text = self._ocio_shader_desc.getShaderText()
        frag_src = GLSL_FRAG_OCIO_SRC_FMT.format(ocio_src=ocio_shader_text)

        if not self._build_shader_program_cached(frag_src, input_colorspace, display, view):
            raise RuntimeError("Failed to build shader program")
        timings["shader_compile"] = (time.time() - t) * 1000

        # === LUT TEXTURE ALLOCATION ===
        t = time.time()
        if not self._allocate_ocio_tex():
            raise RuntimeError("Failed to allocate OCIO textures")
        timings["lut_allocation"] = (time.time() - t) * 1000

        # === RENDER SETUP ===
        t = time.time()
        GL.glBindFramebuffer(GL.GL_FRAMEBUFFER, self._framebuffer)
        GL.glViewport(0, 0, width, height)
        GL.glClearColor(0.0, 0.0, 0.0, 1.0)
        GL.glClear(GL.GL_COLOR_BUFFER_BIT)
        GL.glUseProgram(self._shader_program)

        mvp = np.identity(4, dtype=np.float32)
        mvp_loc = GL.glGetUniformLocation(self._shader_program, "mvpMat")
        GL.glUniformMatrix4fv(mvp_loc, 1, GL.GL_FALSE, mvp)

        GL.glActiveTexture(GL.GL_TEXTURE0)
        GL.glBindTexture(GL.GL_TEXTURE_2D, self._image_tex)
        img_tex_loc = GL.glGetUniformLocation(self._shader_program, "imageTex")
        GL.glUniform1i(img_tex_loc, 0)

        self._use_ocio_tex()
        timings["render_setup"] = (time.time() - t) * 1000

        # === DRAW CALL ===
        t = time.time()
        GL.glBindVertexArray(self._vao)
        GL.glDrawElements(GL.GL_TRIANGLES, 6, GL.GL_UNSIGNED_INT, ctypes.c_void_p(0))
        GL.glFinish()  # Force GPU to complete rendering
        timings["draw_call"] = (time.time() - t) * 1000

        # === PIXEL READBACK ===
        t = time.time()
        GL.glReadBuffer(GL.GL_COLOR_ATTACHMENT0)
        result = GL.glReadPixels(0, 0, width, height, GL.GL_RGBA, GL.GL_FLOAT)
        result = np.frombuffer(result, dtype=np.float32).reshape((height, width, 4))
        result = np.flipud(result)
        timings["pixel_readback"] = (time.time() - t) * 1000

        timings["total"] = (time.time() - t_start) * 1000
        logger.info(f"GPU rendering complete: {width}x{height}x4")

        return result, timings

    def _set_ocio_tex_params(self, tex_type: int, interpolation: int) -> None:
        """Set texture parameters based on interpolation mode.

        Args:
            tex_type: OpenGL texture type (GL_TEXTURE_1D/2D/3D).
            interpolation: OCIO interpolation enum.
        """
        if interpolation == ocio.INTERP_NEAREST:
            GL.glTexParameteri(tex_type, GL.GL_TEXTURE_MIN_FILTER, GL.GL_NEAREST)
            GL.glTexParameteri(tex_type, GL.GL_TEXTURE_MAG_FILTER, GL.GL_NEAREST)
        else:
            GL.glTexParameteri(tex_type, GL.GL_TEXTURE_MIN_FILTER, GL.GL_LINEAR)
            GL.glTexParameteri(tex_type, GL.GL_TEXTURE_MAG_FILTER, GL.GL_LINEAR)

        # Edge clamping
        GL.glTexParameteri(tex_type, GL.GL_TEXTURE_WRAP_S, GL.GL_CLAMP_TO_EDGE)
        if tex_type in [GL.GL_TEXTURE_2D, GL.GL_TEXTURE_3D]:
            GL.glTexParameteri(tex_type, GL.GL_TEXTURE_WRAP_T, GL.GL_CLAMP_TO_EDGE)
        if tex_type == GL.GL_TEXTURE_3D:
            GL.glTexParameteri(tex_type, GL.GL_TEXTURE_WRAP_R, GL.GL_CLAMP_TO_EDGE)

    def _allocate_ocio_tex(self) -> bool:
        """Allocate GPU textures for OCIO LUTs.

        Returns:
            True if successful.
        """
        if not self._ocio_shader_desc:
            return False

        self._del_ocio_tex()
        tex_index = self._ocio_tex_start_index

        # Process 3D textures (cube LUTs)
        for tex_info in self._ocio_shader_desc.get3DTextures():
            try:
                tex_data = tex_info.getValues()

                tex = GL.glGenTextures(1)
                GL.glActiveTexture(GL.GL_TEXTURE0 + tex_index)
                GL.glBindTexture(GL.GL_TEXTURE_3D, tex)

                self._set_ocio_tex_params(GL.GL_TEXTURE_3D, tex_info.interpolation)

                GL.glTexImage3D(
                    GL.GL_TEXTURE_3D,
                    0,
                    GL.GL_RGB32F,
                    tex_info.edgeLen,
                    tex_info.edgeLen,
                    tex_info.edgeLen,
                    0,
                    GL.GL_RGB,
                    GL.GL_FLOAT,
                    tex_data,
                )

                self._ocio_tex_ids.append(
                    (
                        tex,
                        tex_info.textureName,
                        tex_info.samplerName,
                        GL.GL_TEXTURE_3D,
                        tex_index,
                    )
                )
                tex_index += 1

                logger.info(
                    f"Allocated 3D LUT: {tex_info.textureName} ({tex_info.edgeLen}^3) at unit {tex_index - 1}"
                )
            except Exception as e:
                logger.error(f"Failed to allocate 3D texture: {e}")
                return False

        # Process 1D/2D textures
        for tex_info in self._ocio_shader_desc.getTextures():
            try:
                tex_data = tex_info.getValues()

                # Determine format based on channel count
                if tex_info.channel == self._ocio_shader_desc.TEXTURE_RED_CHANNEL:
                    internal_fmt = GL.GL_R32F
                    fmt = GL.GL_RED
                else:
                    internal_fmt = GL.GL_RGB32F
                    fmt = GL.GL_RGB

                tex = GL.glGenTextures(1)
                GL.glActiveTexture(GL.GL_TEXTURE0 + tex_index)

                if tex_info.dimensions == self._ocio_shader_desc.TEXTURE_2D:
                    tex_type = GL.GL_TEXTURE_2D
                    GL.glBindTexture(tex_type, tex)
                    self._set_ocio_tex_params(tex_type, tex_info.interpolation)

                    GL.glTexImage2D(
                        tex_type,
                        0,
                        internal_fmt,
                        tex_info.width,
                        tex_info.height,
                        0,
                        fmt,
                        GL.GL_FLOAT,
                        tex_data,
                    )

                    logger.info(
                        f"Allocated 2D LUT: {tex_info.textureName} ({tex_info.width}x{tex_info.height}) at unit {tex_index}"
                    )
                else:
                    tex_type = GL.GL_TEXTURE_1D
                    GL.glBindTexture(tex_type, tex)
                    self._set_ocio_tex_params(tex_type, tex_info.interpolation)

                    GL.glTexImage1D(
                        tex_type,
                        0,
                        internal_fmt,
                        tex_info.width,
                        0,
                        fmt,
                        GL.GL_FLOAT,
                        tex_data,
                    )

                    logger.info(
                        f"Allocated 1D LUT: {tex_info.textureName} ({tex_info.width}) at unit {tex_index}"
                    )

                self._ocio_tex_ids.append(
                    (tex, tex_info.textureName, tex_info.samplerName, tex_type, tex_index)
                )
                tex_index += 1

            except Exception as e:
                logger.error(f"Failed to allocate 1D/2D texture: {e}")
                return False

        return True

    def _del_ocio_tex(self) -> None:
        """Delete all OCIO LUT textures from GPU memory."""
        if self._ocio_tex_ids:
            tex_handles = [tid[0] for tid in self._ocio_tex_ids]
            GL.glDeleteTextures(tex_handles)
            self._ocio_tex_ids.clear()
            logger.info("Deleted OCIO textures")

    def _use_ocio_tex(self) -> None:
        """Bind all OCIO LUT textures to the shader program."""
        for tex, tex_name, sampler_name, tex_type, tex_index in self._ocio_tex_ids:
            GL.glActiveTexture(GL.GL_TEXTURE0 + tex_index)
            GL.glBindTexture(tex_type, tex)
            sampler_loc = GL.glGetUniformLocation(self._shader_program, sampler_name)
            GL.glUniform1i(sampler_loc, tex_index)

        logger.debug(f"Bound {len(self._ocio_tex_ids)} OCIO textures")

    def cleanup(self) -> None:
        """Release GPU resources."""
        self._del_ocio_tex()
        if self._shader_program:
            GL.glDeleteProgram(self._shader_program)
        if self._vao:
            GL.glDeleteVertexArrays(1, [self._vao])
        if self._framebuffer:
            GL.glDeleteFramebuffers(1, [self._framebuffer])
        if self._renderbuffer:
            GL.glDeleteRenderbuffers(1, [self._renderbuffer])
        if self._image_tex:
            GL.glDeleteTextures([self._image_tex])

        logger.info("GPU resources cleaned up")
