"""GPU-accelerated ACES-to-display transforms for PyTorch tensors.

This module provides pure GPU processing for ACES color space transforms
using OpenGL shaders generated by OCIO. All I/O and transforms happen on GPU.
"""

from __future__ import annotations

import ctypes
import logging
from typing import Optional, Tuple

import numpy as np
import torch
import PyOpenColorIO as ocio
from OpenGL import GL

try:
    from OpenGL.EGL import (
        eglGetDisplay,
        eglInitialize,
        eglChooseConfig,
        eglCreateContext,
        eglMakeCurrent,
        eglSwapBuffers,
        eglCreatePbufferSurface,
        eglBindAPI,
    )
    from OpenGL.EGL import (
        EGL_OPENGL_API,
        EGL_OPENGL_BIT,
        EGL_SURFACE_TYPE,
        EGL_PBUFFER_BIT,
        EGL_RENDERABLE_TYPE,
        EGL_RED_SIZE,
        EGL_GREEN_SIZE,
        EGL_BLUE_SIZE,
        EGL_ALPHA_SIZE,
        EGL_DEPTH_SIZE,
        EGL_NONE,
        EGL_DEFAULT_DISPLAY,
        EGL_CONTEXT_CLIENT_VERSION,
    )
    EGL_AVAILABLE = True
except ImportError:
    EGL_AVAILABLE = False

logger = logging.getLogger(__name__)


# GLSL Shader Sources
GLSL_VERT_SRC = """#version 400 core
uniform mat4 mvpMat;
in vec3 in_position;
in vec2 in_texCoord;

out vec2 vert_texCoord;

void main() {
    vert_texCoord = in_texCoord;
    gl_Position = mvpMat * vec4(in_position, 1.0);
}
"""

GLSL_FRAG_OCIO_SRC_FMT = """#version 400 core
uniform sampler2D imageTex;
in vec2 vert_texCoord;

out vec4 frag_color;

{ocio_src}

void main() {{
    vec4 inColor = texture(imageTex, vert_texCoord);
    vec4 outColor = OCIOMain(inColor);
    frag_color = outColor;
}}
"""


class GPUTorchProcessor:
    """GPU processor for OCIO ACES-to-display transforms on PyTorch tensors.
    
    Provides headless GPU rendering using OpenGL/EGL and OCIO shaders.
    All processing happens on GPU; tensors in, tensors out.
    
    Example:
        >>> processor = GPUTorchProcessor()
        >>> aces_tensor = torch.randn(1024, 1024, 3, device="cuda")
        >>> srgb_32bit, srgb_8bit = processor.apply_ocio_torch(
        ...     aces_tensor,
        ...     input_cs="ACES2065-1",
        ...     display="sRGB - Display"
        ... )
    """

    def __init__(self, headless: bool = True) -> None:
        """Initialize GPU processor.

        Args:
            headless: If True, use EGL for headless rendering.

        Raises:
            RuntimeError: If OpenGL initialization fails.
        """
        self._gl_ready = False
        self._headless = headless
        self._display = None
        self._surface = None
        self._context = None

        # OpenGL resources
        self._shader_program: Optional[int] = None
        self._vao: Optional[int] = None
        self._image_tex: Optional[int] = None
        self._output_tex: Optional[int] = None
        self._framebuffer: Optional[int] = None
        self._renderbuffer: Optional[int] = None

        # OCIO resources
        self._ocio_shader_desc: Optional[ocio.GpuShaderDesc] = None
        self._ocio_tex_ids: list = []
        self._ocio_uniform_ids: dict = {}
        self._ocio_tex_start_index = 1

        # Shader cache: (input_cs, display, view) -> compiled_program_id
        self._shader_cache: dict = {}
        self._current_cache_key: Optional[tuple] = None

        # Image metadata
        self._image_width = 0
        self._image_height = 0

        self._initialize_gl()

    def _initialize_gl(self) -> None:
        """Initialize OpenGL context and resources."""
        if self._headless and EGL_AVAILABLE:
            self._initialize_egl()
        else:
            logger.warning(
                "EGL not available; assuming display context exists (interactive mode)"
            )
            self._gl_ready = True

    def _initialize_egl(self) -> None:
        """Initialize EGL context for headless rendering."""
        try:
             # Important: In some environments, we MUST use EGL_PLATFORM_SURFACELESS_MESA
             # or EGL_DEFAULT_DISPLAY. We try to be as generic as possible.
            eglBindAPI(EGL_OPENGL_API)
            
            # Use EGL_DEFAULT_DISPLAY as a starting point
            self._display = eglGetDisplay(EGL_DEFAULT_DISPLAY)
            
            if not self._display or self._display == -1: 
                 raise RuntimeError("eglGetDisplay(EGL_DEFAULT_DISPLAY) returned invalid handle")

            major, minor = ctypes.c_int(), ctypes.c_int()
            
            # NVIDIA driver on headless nodes often requires no-display initialization.
            # We try standard initialization first.
            try:
                if not eglInitialize(self._display, major, minor):
                    raise RuntimeError("Standard eglInitialize returned False")
            except Exception as e:
                logger.warning(f"Default eglInitialize failed: {e}. Trying fallback display 0...")
                self._display = eglGetDisplay(0)
                if not eglInitialize(self._display, major, minor):
                    # One last attempt: null display
                    self._display = eglGetDisplay(None)
                    if not eglInitialize(self._display, major, minor):
                         raise RuntimeError("All eglInitialize attempts failed (Default, 0, None)")

            logger.info(f"EGL initialized: version {major.value}.{minor.value}")

            config_attribs = [
                EGL_SURFACE_TYPE,
                EGL_PBUFFER_BIT,
                EGL_RENDERABLE_TYPE,
                EGL_OPENGL_BIT,
                EGL_RED_SIZE,
                8,
                EGL_GREEN_SIZE,
                8,
                EGL_BLUE_SIZE,
                8,
                EGL_ALPHA_SIZE,
                8,
                EGL_DEPTH_SIZE,
                24,
                EGL_NONE,
            ]
            config_attribs_array = (ctypes.c_int * len(config_attribs))(*config_attribs)

            config = ctypes.c_void_p()
            config_count = ctypes.c_int()

            if not eglChooseConfig(
                self._display,
                config_attribs_array,
                ctypes.byref(config),
                1,
                ctypes.byref(config_count),
            ):
                raise RuntimeError("Could not choose EGL config")

            context_attribs = [EGL_CONTEXT_CLIENT_VERSION, 4, EGL_NONE]
            context_attribs_array = (ctypes.c_int * len(context_attribs))(*context_attribs)

            self._context = eglCreateContext(
                self._display, config, None, context_attribs_array
            )

            if not self._context:
                raise RuntimeError("Could not create EGL context")

            surface_attribs = [
                12344,  # EGL_WIDTH
                1024,
                12345,  # EGL_HEIGHT
                1024,
                EGL_NONE,
            ]
            surface_attribs_array = (ctypes.c_int * len(surface_attribs))(*surface_attribs)

            self._surface = eglCreatePbufferSurface(
                self._display, config, surface_attribs_array
            )

            if not self._surface:
                raise RuntimeError("Could not create EGL pbuffer surface")

            if not eglMakeCurrent(
                self._display, self._surface, self._surface, self._context
            ):
                raise RuntimeError("Could not make EGL context current")

            logger.info("EGL headless context initialized successfully")
            self._gl_ready = True

        except Exception as e:
            logger.error(f"EGL initialization failed: {e}")
            raise RuntimeError(f"Failed to initialize EGL: {e}")

    def _compile_shader(self, glsl_src: str, shader_type: int) -> Optional[int]:
        """Compile GLSL shader.

        Args:
            glsl_src: GLSL source code.
            shader_type: GL_VERTEX_SHADER or GL_FRAGMENT_SHADER.

        Returns:
            Shader program ID or None if compilation fails.
        """
        shader = GL.glCreateShader(shader_type)
        GL.glShaderSource(shader, glsl_src)
        GL.glCompileShader(shader)

        if not GL.glGetShaderiv(shader, GL.GL_COMPILE_STATUS):
            log = GL.glGetShaderInfoLog(shader)
            logger.error(f"Shader compilation failed: {log}")
            return None

        return shader

    def _build_shader_program_cached(
        self, frag_src: str, input_cs: str, display: str, view: str
    ) -> bool:
        """Build shader program with caching.

        Caches compiled shaders by (input_colorspace, display, view) to avoid
        recompiling for repeated transforms.

        Args:
            frag_src: Fragment shader source code.
            input_cs: Input color space name (for cache key).
            display: Display device name (for cache key).
            view: View transform name (for cache key).

        Returns:
            True if successful (either cached or newly compiled).
        """
        cache_key = (input_cs, display, view)

        if cache_key in self._shader_cache:
            self._shader_program = self._shader_cache[cache_key]
            self._current_cache_key = cache_key
            logger.debug(f"Shader program cache hit: {cache_key}")
            return True

        if not self._build_shader_program(frag_src):
            return False

        self._shader_cache[cache_key] = self._shader_program
        self._current_cache_key = cache_key
        logger.info(f"Shader program cached: {cache_key}")
        return True

    def clear_shader_cache(self) -> None:
        """Clear all cached shader programs."""
        for prog_id in self._shader_cache.values():
            GL.glDeleteProgram(prog_id)
        self._shader_cache.clear()
        self._current_cache_key = None
        logger.info("Shader cache cleared")

    def _build_shader_program(self, frag_src: str) -> bool:
        """Build complete shader program.

        Args:
            frag_src: Fragment shader source code.

        Returns:
            True if successful, False otherwise.
        """
        if not self._gl_ready:
            return False

        vert = self._compile_shader(GLSL_VERT_SRC, GL.GL_VERTEX_SHADER)
        if not vert:
            return False

        frag = self._compile_shader(frag_src, GL.GL_FRAGMENT_SHADER)
        if not frag:
            GL.glDeleteShader(vert)
            return False

        program = GL.glCreateProgram()
        GL.glAttachShader(program, vert)
        GL.glAttachShader(program, frag)

        GL.glBindAttribLocation(program, 0, "in_position")
        GL.glBindAttribLocation(program, 1, "in_texCoord")

        GL.glLinkProgram(program)

        if not GL.glGetProgramiv(program, GL.GL_LINK_STATUS):
            log = GL.glGetProgramInfoLog(program)
            logger.error(f"Shader program linking failed: {log}")
            GL.glDeleteProgram(program)
            return False

        if self._shader_program:
            GL.glDeleteProgram(self._shader_program)

        self._shader_program = program
        GL.glDeleteShader(vert)
        GL.glDeleteShader(frag)

        logger.debug("Shader program built successfully")
        return True

    def _setup_quad_geometry(self) -> bool:
        """Set up screen-aligned quad for rendering.

        Returns:
            True if successful.
        """
        if self._vao:
            GL.glDeleteVertexArrays(1, [self._vao])

        self._vao = GL.glGenVertexArrays(1)
        GL.glBindVertexArray(self._vao)

        positions = np.array(
            [
                -1.0,
                1.0,
                0.0,
                1.0,
                1.0,
                0.0,
                1.0,
                -1.0,
                0.0,
                -1.0,
                -1.0,
                0.0,
            ],
            dtype=np.float32,
        )

        texcoords = np.array(
            [
                0.0,
                1.0,
                1.0,
                1.0,
                1.0,
                0.0,
                0.0,
                0.0,
            ],
            dtype=np.float32,
        )

        indices = np.array([0, 1, 2, 0, 2, 3], dtype=np.uint32)

        pos_vbo, tc_vbo, idx_vbo = GL.glGenBuffers(3)

        GL.glBindBuffer(GL.GL_ARRAY_BUFFER, pos_vbo)
        GL.glBufferData(GL.GL_ARRAY_BUFFER, positions.nbytes, positions, GL.GL_STATIC_DRAW)
        GL.glVertexAttribPointer(0, 3, GL.GL_FLOAT, GL.GL_FALSE, 0, ctypes.c_void_p(0))
        GL.glEnableVertexAttribArray(0)

        GL.glBindBuffer(GL.GL_ARRAY_BUFFER, tc_vbo)
        GL.glBufferData(GL.GL_ARRAY_BUFFER, texcoords.nbytes, texcoords, GL.GL_STATIC_DRAW)
        GL.glVertexAttribPointer(1, 2, GL.GL_FLOAT, GL.GL_FALSE, 0, ctypes.c_void_p(0))
        GL.glEnableVertexAttribArray(1)

        GL.glBindBuffer(GL.GL_ELEMENT_ARRAY_BUFFER, idx_vbo)
        GL.glBufferData(GL.GL_ELEMENT_ARRAY_BUFFER, indices.nbytes, indices, GL.GL_STATIC_DRAW)

        GL.glBindVertexArray(0)
        return True

    def _setup_framebuffer(self, width: int, height: int) -> bool:
        """Set up framebuffer for offscreen rendering.

        Args:
            width: Render target width.
            height: Render target height.

        Returns:
            True if successful.
        """
        if self._output_tex:
            GL.glDeleteTextures([self._output_tex])

        self._output_tex = GL.glGenTextures(1)
        GL.glBindTexture(GL.GL_TEXTURE_2D, self._output_tex)
        GL.glTexImage2D(
            GL.GL_TEXTURE_2D,
            0,
            GL.GL_RGB32F,
            width,
            height,
            0,
            GL.GL_RGB,
            GL.GL_FLOAT,
            None,
        )
        GL.glTexParameteri(GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MIN_FILTER, GL.GL_LINEAR)
        GL.glTexParameteri(GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MAG_FILTER, GL.GL_LINEAR)
        GL.glBindTexture(GL.GL_TEXTURE_2D, 0)

        if self._framebuffer:
            GL.glDeleteFramebuffers(1, [self._framebuffer])

        self._framebuffer = GL.glGenFramebuffers(1)
        GL.glBindFramebuffer(GL.GL_FRAMEBUFFER, self._framebuffer)
        GL.glFramebufferTexture2D(
            GL.GL_FRAMEBUFFER,
            GL.GL_COLOR_ATTACHMENT0,
            GL.GL_TEXTURE_2D,
            self._output_tex,
            0,
        )

        if self._renderbuffer:
            GL.glDeleteRenderbuffers(1, [self._renderbuffer])

        self._renderbuffer = GL.glGenRenderbuffers(1)
        GL.glBindRenderbuffer(GL.GL_RENDERBUFFER, self._renderbuffer)
        GL.glRenderbufferStorage(GL.GL_RENDERBUFFER, GL.GL_DEPTH_COMPONENT32F, width, height)
        GL.glFramebufferRenderbuffer(
            GL.GL_FRAMEBUFFER, GL.GL_DEPTH_ATTACHMENT, GL.GL_RENDERBUFFER, self._renderbuffer
        )

        if GL.glCheckFramebufferStatus(GL.GL_FRAMEBUFFER) != GL.GL_FRAMEBUFFER_COMPLETE:
            logger.error("Framebuffer incomplete")
            return False

        GL.glBindFramebuffer(GL.GL_FRAMEBUFFER, 0)
        return True

    def _set_ocio_tex_params(self, tex_type: int, interpolation: int) -> None:
        """Set texture parameters based on interpolation mode.

        Args:
            tex_type: OpenGL texture type (GL_TEXTURE_1D/2D/3D).
            interpolation: OCIO interpolation enum.
        """
        if interpolation == ocio.INTERP_NEAREST:
            GL.glTexParameteri(tex_type, GL.GL_TEXTURE_MIN_FILTER, GL.GL_NEAREST)
            GL.glTexParameteri(tex_type, GL.GL_TEXTURE_MAG_FILTER, GL.GL_NEAREST)
        else:
            GL.glTexParameteri(tex_type, GL.GL_TEXTURE_MIN_FILTER, GL.GL_LINEAR)
            GL.glTexParameteri(tex_type, GL.GL_TEXTURE_MAG_FILTER, GL.GL_LINEAR)

        GL.glTexParameteri(tex_type, GL.GL_TEXTURE_WRAP_S, GL.GL_CLAMP_TO_EDGE)
        if tex_type in [GL.GL_TEXTURE_2D, GL.GL_TEXTURE_3D]:
            GL.glTexParameteri(tex_type, GL.GL_TEXTURE_WRAP_T, GL.GL_CLAMP_TO_EDGE)
        if tex_type == GL.GL_TEXTURE_3D:
            GL.glTexParameteri(tex_type, GL.GL_TEXTURE_WRAP_R, GL.GL_CLAMP_TO_EDGE)

    def _allocate_ocio_tex(self) -> bool:
        """Allocate GPU textures for OCIO LUTs.

        Returns:
            True if successful.
        """
        if not self._ocio_shader_desc:
            return False

        self._del_ocio_tex()
        tex_index = self._ocio_tex_start_index

        for tex_info in self._ocio_shader_desc.get3DTextures():
            try:
                tex_data = tex_info.getValues()

                tex = GL.glGenTextures(1)
                GL.glActiveTexture(GL.GL_TEXTURE0 + tex_index)
                GL.glBindTexture(GL.GL_TEXTURE_3D, tex)

                self._set_ocio_tex_params(GL.GL_TEXTURE_3D, tex_info.interpolation)

                GL.glTexImage3D(
                    GL.GL_TEXTURE_3D,
                    0,
                    GL.GL_RGB32F,
                    tex_info.edgeLen,
                    tex_info.edgeLen,
                    tex_info.edgeLen,
                    0,
                    GL.GL_RGB,
                    GL.GL_FLOAT,
                    tex_data,
                )

                self._ocio_tex_ids.append(
                    (
                        tex,
                        tex_info.textureName,
                        tex_info.samplerName,
                        GL.GL_TEXTURE_3D,
                        tex_index,
                    )
                )
                tex_index += 1

                logger.debug(
                    f"Allocated 3D LUT: {tex_info.textureName} ({tex_info.edgeLen}^3) at unit {tex_index - 1}"
                )
            except Exception as e:
                logger.error(f"Failed to allocate 3D texture: {e}")
                return False

        for tex_info in self._ocio_shader_desc.getTextures():
            try:
                tex_data = tex_info.getValues()

                if tex_info.channel == self._ocio_shader_desc.TEXTURE_RED_CHANNEL:
                    internal_fmt = GL.GL_R32F
                    fmt = GL.GL_RED
                else:
                    internal_fmt = GL.GL_RGB32F
                    fmt = GL.GL_RGB

                tex = GL.glGenTextures(1)
                GL.glActiveTexture(GL.GL_TEXTURE0 + tex_index)

                if tex_info.dimensions == self._ocio_shader_desc.TEXTURE_2D:
                    tex_type = GL.GL_TEXTURE_2D
                    GL.glBindTexture(tex_type, tex)
                    self._set_ocio_tex_params(tex_type, tex_info.interpolation)

                    GL.glTexImage2D(
                        tex_type,
                        0,
                        internal_fmt,
                        tex_info.width,
                        tex_info.height,
                        0,
                        fmt,
                        GL.GL_FLOAT,
                        tex_data,
                    )

                    logger.debug(
                        f"Allocated 2D LUT: {tex_info.textureName} ({tex_info.width}x{tex_info.height}) at unit {tex_index}"
                    )
                else:
                    tex_type = GL.GL_TEXTURE_1D
                    GL.glBindTexture(tex_type, tex)
                    self._set_ocio_tex_params(tex_type, tex_info.interpolation)

                    GL.glTexImage1D(
                        tex_type,
                        0,
                        internal_fmt,
                        tex_info.width,
                        0,
                        fmt,
                        GL.GL_FLOAT,
                        tex_data,
                    )

                    logger.debug(
                        f"Allocated 1D LUT: {tex_info.textureName} ({tex_info.width}) at unit {tex_index}"
                    )

                self._ocio_tex_ids.append(
                    (tex, tex_info.textureName, tex_info.samplerName, tex_type, tex_index)
                )
                tex_index += 1

            except Exception as e:
                logger.error(f"Failed to allocate 1D/2D texture: {e}")
                return False

        return True

    def _del_ocio_tex(self) -> None:
        """Delete all OCIO LUT textures from GPU memory."""
        if self._ocio_tex_ids:
            tex_handles = [tid[0] for tid in self._ocio_tex_ids]
            GL.glDeleteTextures(tex_handles)
            self._ocio_tex_ids.clear()
            logger.debug("Deleted OCIO textures")

    def _use_ocio_tex(self) -> None:
        """Bind all OCIO LUT textures to the shader program."""
        for tex, tex_name, sampler_name, tex_type, tex_index in self._ocio_tex_ids:
            GL.glActiveTexture(GL.GL_TEXTURE0 + tex_index)
            GL.glBindTexture(tex_type, tex)
            sampler_loc = GL.glGetUniformLocation(self._shader_program, sampler_name)
            GL.glUniform1i(sampler_loc, tex_index)

        logger.debug(f"Bound {len(self._ocio_tex_ids)} OCIO textures")

    def apply_ocio_torch(
        self,
        aces_tensor: torch.Tensor,
        input_cs: str = "ACES2065-1",
        display: str = "sRGB - Display",
        view: str = "ACES 2.0 - SDR 100 nits (Rec.709)",
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """Apply OCIO transform to a Torch GPU tensor.

        Args:
            aces_tensor: [H, W, 3] float32 tensor on CUDA.
            input_cs: Source color space.
            display: Target display.
            view: Target view.

        Returns:
            (srgb_32bit: [H, W, 3] float32 on GPU, srgb_8bit: [H, W, 3] uint8 on GPU)

        Raises:
            ValueError: If input tensor is not on CUDA.
            RuntimeError: If GPU processing fails.
        """
        if not self._gl_ready:
            raise RuntimeError("OpenGL not initialized")

        if not aces_tensor.is_cuda:
            raise ValueError("Input tensor must be on CUDA")

        H, W, C = aces_tensor.shape

        if H != self._image_height or W != self._image_width:
            self._image_width = W
            self._image_height = H
            if not self._setup_framebuffer(W, H):
                raise RuntimeError("Failed to setup framebuffer")
            if not self._setup_quad_geometry():
                raise RuntimeError("Failed to setup geometry")

        # Convert tensor to CPU numpy for GPU texture upload
        image_np = aces_tensor.detach().cpu().numpy()

        if self._image_tex:
            GL.glDeleteTextures([self._image_tex])

        self._image_tex = GL.glGenTextures(1)
        GL.glBindTexture(GL.GL_TEXTURE_2D, self._image_tex)
        GL.glTexImage2D(
            GL.GL_TEXTURE_2D, 0, GL.GL_RGB32F, W, H, 0, GL.GL_RGB, GL.GL_FLOAT, image_np.ravel()
        )
        GL.glTexParameteri(GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MIN_FILTER, GL.GL_LINEAR)
        GL.glTexParameteri(GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MAG_FILTER, GL.GL_LINEAR)

        # Build/fetch cached shader
        config = ocio.GetCurrentConfig()
        cache_key = (input_cs, display, view)

        if cache_key not in self._shader_cache:
            processor = config.getProcessor(
                input_cs, display, view, ocio.TRANSFORM_DIR_FORWARD
            )
            gpu_processor = processor.getDefaultGPUProcessor()
            shader_desc = ocio.GpuShaderDesc.CreateShaderDesc(language=ocio.GPU_LANGUAGE_GLSL_4_0)
            gpu_processor.extractGpuShaderInfo(shader_desc)

            frag_src = GLSL_FRAG_OCIO_SRC_FMT.format(ocio_src=shader_desc.getShaderText())
            self._ocio_shader_desc = shader_desc
            if not self._build_shader_program_cached(frag_src, input_cs, display, view):
                raise RuntimeError("Failed to build shader program")
            if not self._allocate_ocio_tex():
                raise RuntimeError("Failed to allocate OCIO textures")

        # Render
        GL.glBindFramebuffer(GL.GL_FRAMEBUFFER, self._framebuffer)
        GL.glViewport(0, 0, W, H)
        GL.glUseProgram(self._shader_cache[cache_key])

        mvp = np.identity(4, dtype=np.float32)
        mvp_loc = GL.glGetUniformLocation(self._shader_cache[cache_key], "mvpMat")
        GL.glUniformMatrix4fv(mvp_loc, 1, GL.GL_FALSE, mvp)

        GL.glActiveTexture(GL.GL_TEXTURE0)
        GL.glBindTexture(GL.GL_TEXTURE_2D, self._image_tex)
        GL.glUniform1i(GL.glGetUniformLocation(self._shader_cache[cache_key], "imageTex"), 0)
        self._use_ocio_tex()

        GL.glClearColor(0.0, 0.0, 0.0, 1.0)
        GL.glClear(GL.GL_COLOR_BUFFER_BIT)

        GL.glBindVertexArray(self._vao)
        GL.glDrawElements(GL.GL_TRIANGLES, 6, GL.GL_UNSIGNED_INT, ctypes.c_void_p(0))
        GL.glFinish()

        # Clean up input texture immediately to save GPU memory
        GL.glDeleteTextures([self._image_tex])
        self._image_tex = None

        # Readback results
        GL.glReadBuffer(GL.GL_COLOR_ATTACHMENT0)
        rgba_32f = GL.glReadPixels(0, 0, W, H, GL.GL_RGB, GL.GL_FLOAT)
        res_32f = np.frombuffer(rgba_32f, dtype=np.float32).reshape((H, W, 3))

        # Create 8-bit quantized version
        res_8u = (np.clip(res_32f, 0.0, 1.0) * 255).astype(np.uint8)

        logger.debug(f"GPU transform complete: {W}x{H}x3 -> float32 + uint8")

        # Create GPU tensors from CPU readbacks
        res_32f_gpu = torch.from_numpy(res_32f.copy()).to(aces_tensor.device)
        res_8u_gpu = torch.from_numpy(res_8u.copy()).to(aces_tensor.device)

        return res_32f_gpu, res_8u_gpu

    def cleanup(self) -> None:
        """Release GPU resources."""
        self._del_ocio_tex()
        if self._shader_program:
            GL.glDeleteProgram(self._shader_program)
        if self._vao:
            GL.glDeleteVertexArrays(1, [self._vao])
        if self._framebuffer:
            GL.glDeleteFramebuffers(1, [self._framebuffer])
        if self._renderbuffer:
            GL.glDeleteRenderbuffers(1, [self._renderbuffer])
        if self._image_tex:
            GL.glDeleteTextures([self._image_tex])
        if self._output_tex:
            GL.glDeleteTextures([self._output_tex])

        logger.info("GPU resources cleaned up")
