# @package _global_


epochs: 10

# Target blurring for clean gradient learning
target_blur:
  start_sigma: 0.0      # Start with blur to focus on core gradients
  end_sigma: 0.0        # End on real images
  anneal_epochs: ${eval:'${epochs} // 2'} 

bit_crunch_contrast_min: 1.0
bit_crunch_contrast_max: 1.0

loss:
  l1_weight: 1.0
  l2_weight: 0.0
  charbonnier_weight: 0.1
  grad_match_weight: 0.0
  total_variation_weight: 0.0
  total_variation_variant: "huber"
