# @package _global_
defaults:
  - mapper  # Inherit everything from the base mapper task
  - _self_

config_name: mapper_dev


# Data specific to ACES mapping
shard_path: "dataset/temp/shards/val"
val_shard_path: "dataset/temp/shards/val"

# Output scoping
output_dir: ./outputs/mapper/training

epochs: 2