# Entry config for Joint training.
# Inherits global system defaults from config.yaml and applies joint task params.

defaults:
  - config
  - task: task_joint
  - _self_

# Training parameters
batch_size: 1
epochs: 20  
learning_rate: 1e-4  
checkpoint_freq: 5        # Checkpoint every 5 epochs
save_top_k: 3             # Keep best 3 performers (PSNR)
resume_ckpt_path: null #/mnt/MKP01/med8_project/LuminaScale/outputs/training/20260412_143228/checkpoints/dequant-epoch=49.ckpt  # Path to checkpoint to resume from (e.g., outputs/training/20260412_143228/checkpoints/dequant-epoch=49.ckpt)
precision: "32"
